---
name: Data-Shark
version: v2.1
author:
  - 'Jack <walzbill@gmail.com>'
abstract: load various Data::Shark modules
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Cache::Cache: 1
  DBI: 1.4
  SQL::Abstract: 1.5
provides:
  Data::Shark:
    file: lib/Data/Shark.pm
    version: v2.1
  Data::Shark::DBI:
    file: lib/Data/Shark/DBI.pm
    version: v2.1
  Data::Shark::DIO:
    file: lib/Data/Shark/DIO.pm
    version: v2.1
  Data::Shark::FIO:
    file: lib/Data/Shark/FIO.pm
    version: v2.1
  Data::Shark::Util:
    file: lib/Data/Shark/Util.pm
    version: v2.1
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
